### ISSUE TITLE
Incorrect Classname: SmartContract\Parameters

### ISSUE THREAD

**Issue by pepijnolivier** [CityOfZion/neo-php#3]
Please see [ContractParameters.php](https://github.com/CityOfZion/neo-php/blob/master/src/SmartContract/)

Note that the filename is `ContractParameters.php` while the class name is `Parameters`.
This is an issue when autoloading via composer.

**Proposed solution**: 
Change the filename from `ContractParameters.php` to `Parameters.php`.

---

Please also see [PSR-4 coding standards](https://www.php-fig.org/psr/psr-4/)
> The terminating class name corresponds to a file name ending in .php.

**Comment by Woodehh** [comment]
Thanks for the PR, I've merged it. Could you run over the code and maybe fix PSR-4 standards for the rest of it?

For example, what happens if you run the ./examples/nep5-functions.php? When i get the package from packagist, i get errors on the neoassets:

```php
PHP Fatal error:  Class 'NeoPHP\NeoAssets' not found in /Users/benjamindebos/Dropbox/LocalDevelopment/test123456/neo-php/examples/nep5-functions.php on line 13

Fatal error: Class 'NeoPHP\NeoAssets' not found in /Users/benjamindebos/Dropbox/LocalDevelopment/test123456/neo-php/examples/nep5-functions.php on line 13
```

Let me know!

**Comment by pepijnolivier** [comment]
Hi, thanks for merging the PR !

I will have a look at the above, and any other composer issues. If it's okay for you, I could run [PHP-Codestyle-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) on this project, to ensure it's adhering to PSR-2 codestyle. (would be a big commit though, mainly codestyle changes!)

I also noticed there are a few docblocks stating `return type: void`, while the function returns something. FYI, these (minor) issues are all reported to me by PHPStorm, because I'm using [PHP inspections](https://github.com/kalessil/phpinspectionsea). It's worth trying, if you're already using PHPStorm.

**Comment by Woodehh** [comment]
That would be awesome! Please do everything that's within your capabilities to make this project even more pretty and better than before :)

**Comment by pepijnolivier** [comment]
Okay, going to do this now !
