### ISSUE TITLE
Getting an incorrect wallet balance for some tokens

### ISSUE THREAD

**Issue by pepijnolivier** [CityOfZion/neo-php#8]
When I request token balances for the following address `Aas3fPV8Q3PxUd3WAjXTNYP5tamqsuQy3V`, I get back an incorrect balance for these tokens:

- ONT
- TNC

How to reproduce:

- Check balance on [NeoScan.io](https://neoscan.io/address/Aas3fPV8Q3PxUd3WAjXTNYP5tamqsuQy3V): ~**11.45 ONT**
- Request balance via neo-php: **2.8 ONT**

```
require 'vendor/autoload.php';

$rpcObject = new \NeoPHP\NeoRPC();
$node = $rpcObject->getFastestNode();
$rpcObject->setNode($node);
$balance = \NeoPHP\NeoNEP5::getTokenBalance($rpcObject, \NeoPHP\Assets\NeoAssets::ASSET_ONT, 'Aas3fPV8Q3PxUd3WAjXTNYP5tamqsuQy3V');

var_dump($balance);
```

**Comment by Woodehh** [comment]
I've just checked this issue; and it seems to work. Make sure you use a quick node and a node that is synchronized. I recommend neo node 2, which is situated in Canada and is pretty quick!

Could you try again:

```php
include("../vendor/autoload.php");

use \NeoPHP\NeoNEP5;
use \NeoPHP\Assets\NeoAssets;

#test net or not
$rpcObject = new \NeoPHP\NeoRPC(true);

#$rpcObject->setNode($rpcObject->getFastestNode());
$rpcObject->setNode("https://seed1.redpulse.com:10331");

//get the NEP5 token balance for TKY
print_r("ONT Balance: ".NeoNEP5::getTokenBalance($rpcObject, NeoAssets::ASSET_ONT, "Aas3fPV8Q3PxUd3WAjXTNYP5tamqsuQy3V")."\n");
```

**Comment by pepijnolivier** [comment]
You are right. The node I was using must not have been synchronized. It works like it should using the node you provided.

I will use this node for now. Cheers !
